#'@title Time Series Extreme Learning Machine (ELM)
#'@description Machine learning technique used for time series forecasting.
#' ELM is a type of feedforward neural network that uses a single hidden layer
#' of randomly generated neurons.
#'@param preprocess normalization
#'@param input_size input size for machine learning model
#'@param nhid ensemble size
#'@param actfun string: defines the type to use, possible values: 'sig',
#' 'radbas', 'tribas', 'relu', 'purelin' (default).
#'@return a `ts_elm` object.
#'@examples trans <- dal_transform()
#'@export
ts_elm <- function(preprocess=NA, input_size=NA, nhid=NA, actfun='purelin') {
  obj <- tsreg_sw(preprocess, input_size)
  if (is.na(nhid))
    nhid <- input_size/3
  obj$nhid <- nhid
  obj$actfun <- as.character(actfun)

  class(obj) <- append("ts_elm", class(obj))
  return(obj)
}

#'@title Set specific parameters of a ts_elm object
#'@description This function takes two arguments: obj, which is an object of the ts_elm class, and params, which is a list of parameters to be updated
#'@param obj object
#'@param params parameters
#'@return The object obj updated with the new parameters
#'@examples trans <- dal_transform()
#'@export
set_params.ts_elm <- function(obj, params) {
  if (!is.null(params$nhid))
    obj$nhid <- params$nhid
  if (!is.null(params$actfun))
    obj$actfun <- as.character(params$actfun)
  return(obj)
}

#'@import elmNNRcpp
#'@title Train an ELM (Extreme Learning Machine) model
#'@description This function takes three arguments: obj, which is an object of the ts_elm class, x, which is an array with the predictor variables, and y, which is a vector with the response variable. After training, the resulting ELM model is stored in the obj object using the model attribute
#'@param obj object
#'@param x input variable
#'@param y output variable
#'@return The obj object updated with the trained model
#'@examples trans <- dal_transform()
#'@export
do_fit.ts_elm <- function(obj, x, y) {
  obj$model <- elmNNRcpp::elm_train(x, y, nhid = obj$nhid, actfun = obj$actfun, init_weights = "uniform_positive", bias = FALSE, verbose = FALSE)
  return(obj)
}

#'@import elmNNRcpp
#'@title Make predictions using a previously trained ELM model
#'@description This function takes obj and x as arguments
#'@param obj object
#'@param x input variable
#'@return A numerical object containing the predictions generated by the ELM model for the predictor variables x.
#'@examples trans <- dal_transform()
#'@export
do_predict.ts_elm <- function(obj, x) {
  if (is.data.frame(x))
    x <- as.matrix(x)
  prediction <- elmNNRcpp::elm_predict(obj$model, x)
  return(prediction)
}
